### ISSUE TITLE
Créer un maquette figma

### ISSUE THREAD

**Issue by Beckomatik** [HeleneGreat/wiki_disney#3]
Je ne sais pas si il y a une méthode pour pusher ça (genre une capture d'écran qu'on mettrait dans le dossier public?), sinon on se l'envoi entre nous dans le teams. Donc possibilité de supprimer cet issue.

**Comment by HeleneGreat** [comment]
il me semble qu'on peut travailler à plusieurs sur le même projet figma

**Comment by HeleneGreat** [comment]
Je push la maquette/wireframe que j'avais fait sur pain pour nous guider dans notre construction
