### ISSUE TITLE
Faire un modèle de base de données

### ISSUE THREAD

**Issue by Beckomatik** [HeleneGreat/wiki_disney#4]
En utilisant https://app.diagrams.net 
Je ne sais pas si on peut se partager le diagramme et travailler à plusieurs dessus, à voir.

**Comment by HeleneGreat** [comment]
J'ai créé une branche et ajouté une première version de l'UML. Par contre je ne sais pas trop comment intégrer les chiffres (1, n, etc....).
On peut tous travailler dessus

**Comment by HeleneGreat** [comment]
Peut-être rajouter une colonne "role" chez les Users :
- role 0 : utilisateur standard
- role 1 : admin = peut ajouter des catégories, voir la liste de tous les articles, supprimer n'importe quel article, supprimer un utilisateur...
