### ISSUE TITLE
Vérifier font awesome

### ISSUE THREAD

**Issue by HeleneGreat** [HeleneGreat/wiki_disney#49]
@Beckomatik tu m'as dit que les Font Awesome n'apparaissaient pas chez toi.
Merci de faire cette petite vérif de ton côté et de me tenir au courant.

- Positionne-toi sur main -> git checkout main
- git pull

Est-ce que maintenant l'icône de la corbeille apparait sur la page d'un article ?
(ton utilisateur doit être connecté et auteur de l'article pour la voir)

**Comment by Beckomatik** [comment]
Résolu : 
J'ai eu à refaire la commande : 
npm install --save-dev @fortawesome/fontawesome-free
